Attribute VB_Name = "globals"
Global Assunto As String
Global Corpo As String
Global TotalEnviado As Integer
Global EmailAgora As String
Global Delay As Integer
Global Ativado As Integer
Global Ultimo As Integer
Global Mails() As String
